import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/navs/Navbar';
import Footer from '@/components/footers/Footer';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
    title: 'Faosy Adebimpe - Software Engineer',
    description: 'Generated by create next app', // give it a description
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" type="image/svg+xml" href="/logo.svg" />
                {/* <link rel="icon" type="image/svg+xml" href="/image/logo.svg" /> */}
            </head>
            <body className={``}>
                <Toaster />
                <Navbar />
                <div className="limit-width">{children}</div>
                <Footer />
            </body>
        </html>
    );
}
